### ISSUE TITLE
Custom prompts to run after a meeting

### ISSUE THREAD

**Issue by chris-miaskowski** [luni-ai/public-roadmap#2]
Custom Prompt Creation

As a meeting host,
I want to be able to create custom prompts for the AI,
So that I can guide the analysis of the meeting transcription according to specific topics or points of interest.
Pre-meeting Custom Prompt Setting

As a meeting host,
I want to set a custom prompt for the AI before the meeting starts,
So that I can prepare in advance for what I'd like the AI to focus on during its analysis.
Post-meeting Custom Prompt Setting

As a meeting host,
I want to be able to set or modify a custom prompt after a meeting has concluded,
So that I can refine the analysis based on what was discussed during the meeting.
Markdown Formatted Summary

As a meeting host,
I want to receive the AI's analysis in a markdown formatted summary,
So that it's organized and easily readable for me and the participants.
Interface for Custom Prompt Creation

As a meeting host,
I want to have a user-friendly interface to create and manage my custom prompts,
So that I can easily guide the AI's analysis without technical barriers.
Predefined Prompts Selection

As a meeting host,
I want to choose from a set of predefined prompts,
So that I can quickly select common topics or points of interest without having to create a custom prompt every time.

**Comment by karol-maciaszek** [comment]
All done except Markdown support. This will be implemented along with next OpenAI-interaction related task.
